data_path: data/advection
dataset_name: Advection
train_resolution: 64
test_resolution: [64, 128, 256, 512, 1024]
in_channels: 1
out_channels: 1
train_size: 900
test_size: 100
dim: 2
n_modes: 16
time_dependent: true
train_batch_size: 64
test_batch_size: 10
pretrain_batch_size: 64