data_path: /cmlscratch/anirudhs/DENO/data/ns_incom
dataset_name: NavierStokesIncompressible
train_resolution: 64
test_resolution: [64, 128, 256]
in_channels: 1
out_channels: 1
train_size: 900
test_size: 100
dim: 3
n_modes: 12
time_dependent: true
train_batch_size: 32
test_batch_size: 2
pretrain_batch_size: 32