defaults:
  - dataset: Advection
  - model: FNO
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

device: ${oc.env:DEVICE,"cuda:0"}
subset_percentage: 20.0
log_dir: ./results
coreset_algorithm: gradmatch
seed: 10
grad_clip: 5.0
overwrite: false
attack: ""
eqn_weight: 0.0
ic_weight: 0.0
nrmse_weight: 1.0
pretrain_epochs: 25
epochs: 500
lr: 1e-3
wandb: true
wandb_project: DENO
wandb_entity: ''
wandb_dir: ./wandb
mask_percentage: 0.2
blur_std: 0.3
simclr_epochs: 100
sample_size_fraction: 0.1
# pretrain_model_save_path: ${log_dir}/models
